### PR TITLE
feat: add nest adapter

### PR DESCRIPTION
**Pull request by ismoiliy98**
_PoC:_ Adds support for nest js express adapter.

---

It just overrides some methods of the original `@nestjs/platform-express`.
The question is whether it should be published as separate packages or kept within `ultimate-express`...

### CODE REVIEW

**Comment by nigrosimone** [comment]
Mhh I think it's better publish as separate package. @dimdenGD what do you things? There are so many meta framework based on express...

**Comment by cesco69** [comment]
@ismoiliy98 why not as a new package into https://github.com/nestjs/nest/tree/master/packages ?

**Comment by dimdenGD** [comment]
Out of scope, it should be a separate package.

**Comment by nigrosimone** [comment]
This is also discussed on NestJS here https://github.com/nestjs/nest/issues/14075 and has a PR here https://github.com/nestjs/nest/pull/14120

**Comment by CornWorld** [comment]
I'm curious about the result of https://github.com/nestjs/nest/pull/14120 actually, this PR is closed and I cannot find any progresses in the Internet actually. 
**Is @Pho3niX90 still working on this idea?**

I'm sorry to add a comment here 'cause I can't find the email addr of Pho3niX90.
Hope someone gives help!

**Comment by Pho3niX90** [comment]
> I'm curious about the result of https://github.com/nestjs/nest/pull/14120 actually, this PR is closed and I cannot find any progresses in the Internet actually. 
> **Is @Pho3niX90 still working on this idea?**
> 
> I'm sorry to add a comment here 'cause I can't find the email addr of Pho3niX90.
> Hope someone gives help!

I haven't made changes to it as yet since it was essentially denied as an integration. The suggestion was to rather create it as a third-party integration. 

The code PRd, was a working example, and using it in a majority of my microservices.

**Comment by nigrosimone** [comment]
> I'm curious about the result of [nestjs/nest#14120](https://github.com/nestjs/nest/pull/14120) actually, this PR is closed and I cannot find any progresses in the Internet actually. **Is @Pho3niX90 still working on this idea?**
> 
> I'm sorry to add a comment here 'cause I can't find the email addr of Pho3niX90. Hope someone gives help!

see https://www.npmjs.com/package/nestjs-ultimate-express

**Pull request closed without merging**
