### PR TITLE
Fix content type on string (also fix compression)

### PR DESCRIPTION
**Pull request by cesco69**

### CODE REVIEW

**Comment by cesco69** [comment]
```
+ ' application/javascript; charset=utf-8\n'
-   ' application/javascript; charset=UTF-8\n'
```

The test is wrong... charset must be lowercase

**Comment by dimdenGD** [comment]
just modify test to lowercase it, case doesn't matter in this header

**Comment by cesco69** [comment]
I don't understand where change it 

:D

**Comment by dimdenGD** [comment]
Now it works without setting header but still doesn't send the second chunk.

**Comment by dimdenGD** [comment]
```js
// must support compression middleware OFF

const express = require("express");
const compression = require("compression");
const net = require("net");

async function sendRequest(method, url) {
    return new Promise((resolve, reject) => {
        const client = new net.Socket();
        const [host, port] = url.split('://')[1].split('/')[0].split(':');
        const path = '/' + url.split('/').slice(3).join('/');

        client.connect(parseInt(port), host, () => {
            let request = `${method} ${path} HTTP/1.1\r\n`;
            request += `Host: ${host}:${port}\r\n`;
            request += `Accept-Encoding: gzip, deflate, br\r\n`;
            
            request += '\r\n';

            client.on('data', data => {
                const rawHttpMessage = data.toString('utf-8');
                const parts = rawHttpMessage.split(/\r?\n\r?\n/);
                const headersPart = parts[0];
                const bodyPart = parts.slice(1).join('\n\n');
                const headersEndIndex = rawHttpMessage.indexOf('\r\n\r\n') + 4; 
                const bodyBuffer = data.slice(headersEndIndex);
                resolve(bodyBuffer);
            });
            
            client.write(request);
        });
    });
}

const app = express();

app.use(compression({
    threshold: 1,
}));

app.get('/abc', (req, res) => {
    res.send('Hello World'.repeat(100));
});

app.listen(13333, async () => {
    console.log('Server is running on port 13333');

    const response = await sendRequest('GET', 'http://localhost:13333/abc');
    console.log(response, '\n', response.toString('utf-8'));

    process.exit(0);

});
```

**Comment by cesco69** [comment]
I don't quite understand this. The problem seems to be that ultimate-express sends the response when "compression" writes the first chunk to the stream, as if it didn't wait for the end. I think this is also normal (that it sends a stream while it's being written) but this is the cause of the problem, the response is complete while the server is still compressing it

**Comment by nigrosimone** [comment]
@dimdenGD compression works is your test wrong, the promise is resolved on first chunk and don't wait for the enad of the response. This is a working test:

```js
// must support compression middleware OFF

const express = require("express");
const compression = require("compression");
const net = require("net");

async function sendRequest(method, url) {
    return new Promise((resolve, reject) => {
        const client = new net.Socket();
        const [host, port] = url.split('://')[1].split('/')[0].split(':');
        const path = '/' + url.split('/').slice(3).join('/');

        client.connect(parseInt(port), host, () => {
            let request = `${method} ${path} HTTP/1.1\r\n`;
            request += `Host: ${host}:${port}\r\n`;
            request += `Accept-Encoding: gzip, deflate, br\r\n`;
            
            request += '\r\n';

            let fullData = '';

            client.on('data', data => {
                fullData += data.toString('utf-8');
            });

            client.on('end', () => {
                const rawHttpMessage = fullData;
                const parts = rawHttpMessage.split(/\r?\n\r?\n/);
                const headersPart = parts[0];
                const bodyPart = parts.slice(1).join('\n\n');
                const headersEndIndex = rawHttpMessage.indexOf('\r\n\r\n') + 4; 
                const bodyBuffer = data.slice(headersEndIndex);
                resolve(bodyBuffer);
            });
            
            client.write(request);
        });
    });
}

const app = express();

app.use(compression({
    threshold: 1,
}));

app.get('/abc', (req, res) => {
    res.send('Hello World'.repeat(100));
});

app.listen(13333, async () => {
    console.log('Server is running on port 13333');

    const response = await sendRequest('GET', 'http://localhost:13333/abc');
    console.log(response, '\n', response.toString('utf-8'));

    process.exit(0);

});
```


```
npm run test

...


ℹ tests 188
ℹ suites 0
ℹ pass 188
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 156621.3569
```

**Comment by dimdenGD** [comment]
Ahh, thank you. Looks like `compression` really works now!

**Pull request merged**
