### PR TITLE
perf: don't parse query if query is empty

### PR DESCRIPTION
**Pull request by cesco69**
No need to parse query if the query is empty

### CODE REVIEW

**Comment by dimdenGD** [comment]
i think it should always return an object

**Comment by cesco69** [comment]
> i think it should always return an object

Yep! I have fixed in https://github.com/dimdenGD/ultimate-express/pull/34/commits/c4a3ada89207889290222aaa314f1b744f4738c5

**Comment by cesco69** [comment]
@dimdenGD with https://github.com/dimdenGD/ultimate-express/pull/32 there are a bit of microoptimizations, you can re-run benchmark? https://github.com/dimdenGD/ultimate-express?tab=readme-ov-file#performance-against-other-frameworks and maybe release a new version on npm?

**Comment by dimdenGD** [comment]
I re-ran the benchmark, and as I expected there has been no noticable improvements from microoptimizations like this.

**Comment by dimdenGD** [comment]
After fixing https://github.com/dimdenGD/ultimate-express/commit/0fabb974f948f43bbd895881fea82ac5be1fda81#commitcomment-148375147 I think it got a little bit faster, but hyper-express also got faster even if I didn't update it, so it might be just my server feeling like being faster today

**Pull request merged**
