### PR TITLE
uNetworking/uWebSockets.js 20.51.0

### PR DESCRIPTION
**Pull request by nigrosimone**
Update uNetworking/uWebSockets.js at 20.51.0 with support for NodeJs 23

### CODE REVIEW

**Comment by nigrosimone** [comment]
@dimdenGD seems uNetworking/uWebSockets.js 20.50.0 has changed something. I don't understand what is broken

**Comment by dimdenGD** [comment]
revert package-lock change, remove node 23 as its not supported by uws

**Comment by nigrosimone** [comment]
Only `req.params` is broken. All others featurew works!

**Comment by cesco69** [comment]
Side note. uNetworking/uWebSockets.js 20.50.0 with Node 23 is a bit faster

Requests/sec vs express
```
uNetworking/uWebSockets.js 20.50.0 - NodeJs 23:    10.54x faster
uNetworking/uWebSockets.js 20.49.0 - NodeJs 22:    10.03x faster
```

**Comment by cesco69** [comment]
@nigrosimone and @dimdenGD 

I have debug this script with both version

```js
const express = require("../src/index");

const app = express();

app.get('/:test', (req, res) => {
  res.send(req.params.test); // -------------> undefined
})

app.listen(13333, () => {
  console.log("Server is running at http://localhost:13333");
});
```

when call `GET /xxx` in `20.49.0` the request is handled by `_registerUwsRoute`, in `20.50.0` the request is handled by `createRequestHandler`

image

in `20.50.0` `req.optimizedParams` into router.js `_preprocessRequest()` is undefined

**Comment by nigrosimone** [comment]
v20.50.0 is broken! v20.51.0 works!

**Comment by maxpain** [comment]
When will it be merged?

**Comment by nigrosimone** [comment]
@dimdenGD there are sono differences into benchmark?

**Pull request merged**
