### PR TITLE
_implictHeader must be call writeHeader

### PR DESCRIPTION
**Pull request by cesco69**

### CODE REVIEW

**Comment by cesco69** [comment]
@dimdenGD This PR has magically fixed compression! now it works!

#19

**Comment by dimdenGD** [comment]
Nice! Thank you

**Comment by dimdenGD** [comment]
Hmm, it still doesn't work for me.

```js
// must support compression middleware

const express = require("express");
const compression = require("compression");
const net = require("net");

async function sendRequest(method, url) {
    return new Promise((resolve, reject) => {
        const client = new net.Socket();
        const [host, port] = url.split('://')[1].split('/')[0].split(':');
        const path = '/' + url.split('/').slice(3).join('/');

        client.connect(parseInt(port), host, () => {
            let request = `${method} ${path} HTTP/1.1\r\n`;
            request += `Host: ${host}:${port}\r\n`;
            request += `Accept-Encoding: gzip, deflate, br\r\n`;
            
            request += '\r\n';

            client.on('data', data => {
                resolve(data.toString());
            });
            
            client.write(request);
        });
    });
}

const app = express();

app.use(compression({
    threshold: 1,
}));

app.get('/abc', (req, res) => {
    res.send('Hello World'.repeat(100));
});

app.listen(13333, async () => {
    console.log('Server is running on port 13333');

    const response = await sendRequest('GET', 'http://localhost:13333/abc');
    console.log(response.split('\r\n').slice(-6).join('\r\n'));

    process.exit(0);
});
```

only express actually sends compressed response

**Comment by cesco69** [comment]
@dimdenGD 

image

**Comment by dimdenGD** [comment]
Adding content-type indeed makes it... do something. But Express works even without specifically adding that header, and it must match Express behavior.
But even when I add header 
```js
app.get('/abc', (req, res) => {
    res.set('Content-Type', 'text/plain');
    res.send('Hello World'.repeat(100));
});

```

The body is different, Express body:
image


Ultimate Express body:
image

Second chunk with main data seems to be missing

**Comment by cesco69** [comment]
> But Express works even without specifically adding that header

Express set a content type if not setted https://github.com/expressjs/express/blob/master/lib/response.js#L125

**Comment by dimdenGD** [comment]
uexpress sets it too, just in a different place. I guess it needs to be moved/added somewhere else for compression to catch up to it

**Comment by cesco69** [comment]
ok, I take a look

**Comment by cesco69** [comment]
see https://github.com/dimdenGD/ultimate-express/pull/26

**Pull request merged**
